# Generated by Django 4.1.4 on 2023-07-30 13:32

from django.db import migrations, models
import lawyer_site.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[lawyer_site.validators.validate_letters_only])),
                ('last_name', models.CharField(max_length=20, validators=[lawyer_site.validators.validate_letters_only])),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
    ]
