# Generated by Django 4.1.4 on 2023-08-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
