# Generated by Django 4.1.4 on 2023-08-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_site', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='datetime',
        ),
    ]
