# Generated by Django 4.1.4 on 2023-08-05 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-zА-Яа-я]{2,20}$', 'Името трябва да съдържа само букви!')])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-zА-Яа-я]{2,20}$', 'Името трябва да съдържа само букви!')])),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
